/**
 * A manual mapping of permissions using raw BigInt values.
 * @see https://discord.com/developers/docs/topics/permissions#permissions-bitwise-permission-flags
 */
export const permissions = [
    { name: 'Create Invite', value: (1n << 0n).toString() },
    { name: 'View Channel', value: (1n << 10n).toString() },
    { name: 'Manage Channel', value: (1n << 4n).toString() },
    { name: 'Manage Permissions', value: (1n << 28n).toString() },
    { name: 'Manage Webhooks', value: (1n << 29n).toString() },
    { name: 'Send Messages', value: (1n << 11n).toString() },
    { name: 'Send Messages in Threads', value: (1n << 38n).toString() },
    { name: 'Create Public Threads', value: (1n << 35n).toString() },
    { name: 'Create Private Threads', value: (1n << 36n).toString() },
    { name: 'Embed Links', value: (1n << 14n).toString() },
    { name: 'Attach Files', value: (1n << 15n).toString() },
    { name: 'Add Reactions', value: (1n << 6n).toString() },
    { name: 'Use External Emojis', value: (1n << 18n).toString() },
    { name: 'Use External Stickers', value: (1n << 37n).toString() },
    { name: 'Mention @everyone, @here, and All Roles', value: (1n << 17n).toString() },
    { name: 'Manage Messages', value: (1n << 13n).toString() },
    { name: 'Manage Threads', value: (1n << 34n).toString() },
    { name: 'Read Message History', value: (1n << 16n).toString() },
    { name: 'Send Text-to-Speech Messages', value: (1n << 12n).toString() },
    { name: 'Use Application Commands', value: (1n << 31n).toString() },
    { name: 'Use External Apps', value: (1n << 50n).toString() },
    { name: 'Pin Messages', value: (1n << 45n).toString() },
    { name: 'Connect', value: (1n << 20n).toString() },
    { name: 'Speak', value: (1n << 21n).toString() },
    { name: 'Video', value: (1n << 9n).toString() },
    { name: 'Use Activities', value: (1n << 39n).toString() },
    { name: 'Use Soundboard', value: (1n << 42n).toString() },
    { name: 'Use External Sounds', value: (1n << 44n).toString() },
    { name: 'Use Voice Activity', value: (1n << 22n).toString() },
    { name: 'Priority Speaker', value: (1n << 8n).toString() },
    { name: 'Mute Members', value: (1n << 23n).toString() },
    { name: 'Deafen Members', value: (1n << 24n).toString() },
    { name: 'Move Members', value: (1n << 25n).toString() },
    { name: 'Request to Speak', value: (1n << 32n).toString() },
    { name: 'Create Events', value: (1n << 33n).toString() },
    { name: 'Manage Events', value: (1n << 30n).toString() },
    { name: 'Send Voice Messages', value: (1n << 46n).toString() },
    { name: 'Create Polls', value: (1n << 49n).toString() },
    { name: 'Set Voice Channel Status', value: (1n << 48n).toString() },
];